### PR TITLE
cbfs: fix addition of zero-length files

### PR DESCRIPTION
**Pull request by flammit**
Fixes @MrChromebox issue in Heads with persisting zero-length serial number files.

### CODE REVIEW

**Comment by osresearch** [comment]
returning `NULL` for success seems unergonomic.  it reminds me of `malloc(0)`, which is allowed to return NULL (or a unique pointer), but 99% of the callers do not handle it correctly. In this case `ernno` might be non-zero from a previous failure, so this could spuriously fail.

**Comment by flammit** [comment]
@osresearch sorry that was laziness and yes it doesn't work because of previous `errno`.  PTAL the new force-pushed commit

**Comment by osresearch** [comment]
I think the previous version was fine, just with the addition of explicitly setting `errno=0` in the check for the size.  This avoids a potential race condition toctou in opening the file twice.


```
	*size = st.st_size;
	if (*size == 0) {
		errno = 0; // not a failure
		return NULL;
	}
```

**Comment by flammit** [comment]
Third time's the charm!

**Pull request merged**
